#!/bin/sh

REPO=$HOME/proj/vsim
DB=$HOME/proj/vsim/history

die() {
	echo "$@" >&2 ; exit 1 ;
}

checkout() { (

	local rev="$2"

	test -n "$REPO" ||
		die "REPO is not specifiied"

	case $rev in
		"") rev="" ;;
		*) rev="-b $rev" ;;
	esac

	set -e

	local tmpdir=`mktemp -d`
	cd "$tmpdir"
	echo "Checkouting in $tmpdir" >&2
	( set -x
	  git clone $rev $REPO .
	  ./build-minimal.sh
	)>&2
	echo "$tmpdir"

) }

REV="$1"

test -n "$REV" ||
	die "usage: revtest GIT_REVISION"

REVREC=$DB/`date +"%Y-%m-%d-%H-%M-%S"`-$REV
mkdir -p $REVREC >/dev/null ||
	die "Can't create $REVREC"

(
	checkout $REV | (
		read repo

		echo "Cloned in $repo" >&2
		cd "$repo"

		. ./simenv

		for f in vhdl/*vhd ; do

			echo 
			echo "Running $f"
			echo "==========================="
			echo 

			logdir=`runtest $f`
			name=`cat $logdir/NAME`
			mv $logdir $REVREC/$name
		done
	)

) 2>&1 | tee $REVREC/revtest.log


