/* Generated By:JavaCC: Do not edit this line. FSMParserConstants.java */
package com.prosoft.fsm.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface FSMParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int ABS = 6;
  /** RegularExpression Id. */
  int ACCESS = 7;
  /** RegularExpression Id. */
  int ACROSS = 8;
  /** RegularExpression Id. */
  int ACTION = 9;
  /** RegularExpression Id. */
  int AFTER = 10;
  /** RegularExpression Id. */
  int ALIAS = 11;
  /** RegularExpression Id. */
  int ALL = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int ARCHITECTURE = 14;
  /** RegularExpression Id. */
  int ARRAY = 15;
  /** RegularExpression Id. */
  int ASSERT = 16;
  /** RegularExpression Id. */
  int ATTRIBUTE = 17;
  /** RegularExpression Id. */
  int BEGIN = 18;
  /** RegularExpression Id. */
  int BLOCK = 19;
  /** RegularExpression Id. */
  int BODY = 20;
  /** RegularExpression Id. */
  int BREAK = 21;
  /** RegularExpression Id. */
  int BUFFER = 22;
  /** RegularExpression Id. */
  int BUS = 23;
  /** RegularExpression Id. */
  int CASE = 24;
  /** RegularExpression Id. */
  int COMPONENT = 25;
  /** RegularExpression Id. */
  int CONFIGURATION = 26;
  /** RegularExpression Id. */
  int CONSTANT = 27;
  /** RegularExpression Id. */
  int DISCONNECT = 28;
  /** RegularExpression Id. */
  int DOWNTO = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int ELSIF = 31;
  /** RegularExpression Id. */
  int END = 32;
  /** RegularExpression Id. */
  int ENTITY = 33;
  /** RegularExpression Id. */
  int EXIT = 34;
  /** RegularExpression Id. */
  int FILE = 35;
  /** RegularExpression Id. */
  int FOR = 36;
  /** RegularExpression Id. */
  int FUNCTION = 37;
  /** RegularExpression Id. */
  int GENERATE = 38;
  /** RegularExpression Id. */
  int GENERIC = 39;
  /** RegularExpression Id. */
  int GROUP = 40;
  /** RegularExpression Id. */
  int GUARDED = 41;
  /** RegularExpression Id. */
  int IF = 42;
  /** RegularExpression Id. */
  int IMPURE = 43;
  /** RegularExpression Id. */
  int IN = 44;
  /** RegularExpression Id. */
  int INERTIAL = 45;
  /** RegularExpression Id. */
  int INOUT = 46;
  /** RegularExpression Id. */
  int IS = 47;
  /** RegularExpression Id. */
  int LABEL = 48;
  /** RegularExpression Id. */
  int LIBRARY = 49;
  /** RegularExpression Id. */
  int LINKAGE = 50;
  /** RegularExpression Id. */
  int LITERAL = 51;
  /** RegularExpression Id. */
  int LOOP = 52;
  /** RegularExpression Id. */
  int MAP = 53;
  /** RegularExpression Id. */
  int MOD = 54;
  /** RegularExpression Id. */
  int NAND = 55;
  /** RegularExpression Id. */
  int NATURE = 56;
  /** RegularExpression Id. */
  int NEW = 57;
  /** RegularExpression Id. */
  int NEXT = 58;
  /** RegularExpression Id. */
  int NOISE = 59;
  /** RegularExpression Id. */
  int NOR = 60;
  /** RegularExpression Id. */
  int NOT = 61;
  /** RegularExpression Id. */
  int NULL = 62;
  /** RegularExpression Id. */
  int OF = 63;
  /** RegularExpression Id. */
  int ON = 64;
  /** RegularExpression Id. */
  int OPEN = 65;
  /** RegularExpression Id. */
  int OR = 66;
  /** RegularExpression Id. */
  int OTHERS = 67;
  /** RegularExpression Id. */
  int OUT = 68;
  /** RegularExpression Id. */
  int PACKAGE = 69;
  /** RegularExpression Id. */
  int PORT = 70;
  /** RegularExpression Id. */
  int POSTPONED = 71;
  /** RegularExpression Id. */
  int PROCEDURAL = 72;
  /** RegularExpression Id. */
  int PROCEDURE = 73;
  /** RegularExpression Id. */
  int PROCESS = 74;
  /** RegularExpression Id. */
  int PURE = 75;
  /** RegularExpression Id. */
  int QUANTITY = 76;
  /** RegularExpression Id. */
  int RANGE = 77;
  /** RegularExpression Id. */
  int RECORD = 78;
  /** RegularExpression Id. */
  int REGISTER = 79;
  /** RegularExpression Id. */
  int REJECT = 80;
  /** RegularExpression Id. */
  int REM = 81;
  /** RegularExpression Id. */
  int REPORT = 82;
  /** RegularExpression Id. */
  int RETURN = 83;
  /** RegularExpression Id. */
  int ROL = 84;
  /** RegularExpression Id. */
  int ROR = 85;
  /** RegularExpression Id. */
  int SELECT = 86;
  /** RegularExpression Id. */
  int SEVERITY = 87;
  /** RegularExpression Id. */
  int SIGNAL = 88;
  /** RegularExpression Id. */
  int SHARED = 89;
  /** RegularExpression Id. */
  int SLA = 90;
  /** RegularExpression Id. */
  int SLL = 91;
  /** RegularExpression Id. */
  int SPECTRUM = 92;
  /** RegularExpression Id. */
  int SRA = 93;
  /** RegularExpression Id. */
  int SRL = 94;
  /** RegularExpression Id. */
  int SUBNATURE = 95;
  /** RegularExpression Id. */
  int SUBTYPE = 96;
  /** RegularExpression Id. */
  int TERMINAL = 97;
  /** RegularExpression Id. */
  int THEN = 98;
  /** RegularExpression Id. */
  int THROUGH = 99;
  /** RegularExpression Id. */
  int TO = 100;
  /** RegularExpression Id. */
  int TOLERANCE = 101;
  /** RegularExpression Id. */
  int TRANSPORT = 102;
  /** RegularExpression Id. */
  int TYPE = 103;
  /** RegularExpression Id. */
  int UNAFFECTED = 104;
  /** RegularExpression Id. */
  int UNITS = 105;
  /** RegularExpression Id. */
  int UNTIL = 106;
  /** RegularExpression Id. */
  int USE = 107;
  /** RegularExpression Id. */
  int VARIABLE = 108;
  /** RegularExpression Id. */
  int WAIT = 109;
  /** RegularExpression Id. */
  int WHEN = 110;
  /** RegularExpression Id. */
  int WHILE = 111;
  /** RegularExpression Id. */
  int WITH = 112;
  /** RegularExpression Id. */
  int XNOR = 113;
  /** RegularExpression Id. */
  int XOR = 114;
  /** RegularExpression Id. */
  int upper_case_letter = 115;
  /** RegularExpression Id. */
  int lower_case_letter = 116;
  /** RegularExpression Id. */
  int digit = 117;
  /** RegularExpression Id. */
  int extended_digit = 118;
  /** RegularExpression Id. */
  int special_character = 119;
  /** RegularExpression Id. */
  int str_special_character = 120;
  /** RegularExpression Id. */
  int other_special_character = 121;
  /** RegularExpression Id. */
  int format_effector = 122;
  /** RegularExpression Id. */
  int base_specifier = 123;
  /** RegularExpression Id. */
  int underline = 124;
  /** RegularExpression Id. */
  int letter = 125;
  /** RegularExpression Id. */
  int letter_or_digit = 126;
  /** RegularExpression Id. */
  int integer = 127;
  /** RegularExpression Id. */
  int base = 128;
  /** RegularExpression Id. */
  int based_integer = 129;
  /** RegularExpression Id. */
  int based_literal = 130;
  /** RegularExpression Id. */
  int basic_character = 131;
  /** RegularExpression Id. */
  int str_basic_character = 132;
  /** RegularExpression Id. */
  int basic_graphic_character = 133;
  /** RegularExpression Id. */
  int str_basic_graphic_character = 134;
  /** RegularExpression Id. */
  int basic_identifier = 135;
  /** RegularExpression Id. */
  int bit_string_literal = 136;
  /** RegularExpression Id. */
  int bit_value = 137;
  /** RegularExpression Id. */
  int character_literal = 138;
  /** RegularExpression Id. */
  int decimal_literal = 139;
  /** RegularExpression Id. */
  int exponent = 140;
  /** RegularExpression Id. */
  int extended_identifier = 141;
  /** RegularExpression Id. */
  int graphic_character = 142;
  /** RegularExpression Id. */
  int str_graphic_character = 143;
  /** RegularExpression Id. */
  int string_literal = 144;
  /** RegularExpression Id. */
  int EXP = 145;
  /** RegularExpression Id. */
  int MUL = 146;
  /** RegularExpression Id. */
  int DIV = 147;
  /** RegularExpression Id. */
  int ADD = 148;
  /** RegularExpression Id. */
  int SUB = 149;
  /** RegularExpression Id. */
  int CONCAT = 150;
  /** RegularExpression Id. */
  int EQ = 151;
  /** RegularExpression Id. */
  int NEQ = 152;
  /** RegularExpression Id. */
  int GE = 153;
  /** RegularExpression Id. */
  int LE = 154;
  /** RegularExpression Id. */
  int GT = 155;
  /** RegularExpression Id. */
  int LO = 156;
  /** RegularExpression Id. */
  int SEMICOLON = 157;
  /** RegularExpression Id. */
  int OPENBRACE = 158;
  /** RegularExpression Id. */
  int CLOSEDBRACE = 159;
  /** RegularExpression Id. */
  int OPENBRACKET = 160;
  /** RegularExpression Id. */
  int CLOSEDBRACKET = 161;
  /** RegularExpression Id. */
  int EXCLAMATION_MARK = 162;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<COMMENT>",
    "\"abs\"",
    "\"access\"",
    "\"across\"",
    "\"action\"",
    "\"after\"",
    "\"alias\"",
    "\"all\"",
    "\"and\"",
    "\"architecture\"",
    "\"array\"",
    "\"assert\"",
    "\"attribute\"",
    "\"begin\"",
    "\"block\"",
    "\"body\"",
    "\"break\"",
    "\"buffer\"",
    "\"bus\"",
    "\"case\"",
    "\"component\"",
    "\"configuration\"",
    "\"constant\"",
    "\"disconnect\"",
    "\"downto\"",
    "\"else\"",
    "\"elsif\"",
    "\"end\"",
    "\"entity\"",
    "\"exit\"",
    "\"file\"",
    "\"for\"",
    "\"function\"",
    "\"generate\"",
    "\"generic\"",
    "\"group\"",
    "\"guarded\"",
    "\"if\"",
    "\"impure\"",
    "\"in\"",
    "\"inertial\"",
    "\"inout\"",
    "\"is\"",
    "\"label\"",
    "\"library\"",
    "\"linkage\"",
    "\"literal\"",
    "\"loop\"",
    "\"map\"",
    "\"mod\"",
    "\"nand\"",
    "\"nature\"",
    "\"new\"",
    "\"next\"",
    "\"noise\"",
    "\"nor\"",
    "\"not\"",
    "\"null\"",
    "\"of\"",
    "\"on\"",
    "\"open\"",
    "\"or\"",
    "\"others\"",
    "\"out\"",
    "\"package\"",
    "\"port\"",
    "\"postponed\"",
    "\"procedural\"",
    "\"procedure\"",
    "\"process\"",
    "\"pure\"",
    "\"quantity\"",
    "\"range\"",
    "\"record\"",
    "\"register\"",
    "\"reject\"",
    "\"rem\"",
    "\"report\"",
    "\"return\"",
    "\"rol\"",
    "\"ror\"",
    "\"select\"",
    "\"severity\"",
    "\"signal\"",
    "\"shared\"",
    "\"sla\"",
    "\"sll\"",
    "\"spectrum\"",
    "\"sra\"",
    "\"srl\"",
    "\"subnature\"",
    "\"subtype\"",
    "\"terminal\"",
    "\"then\"",
    "\"through\"",
    "\"to\"",
    "\"tolerance\"",
    "\"transport\"",
    "\"type\"",
    "\"unaffected\"",
    "\"units\"",
    "\"until\"",
    "\"use\"",
    "\"variable\"",
    "\"wait\"",
    "\"when\"",
    "\"while\"",
    "\"with\"",
    "\"xnor\"",
    "\"xor\"",
    "<upper_case_letter>",
    "<lower_case_letter>",
    "<digit>",
    "<extended_digit>",
    "<special_character>",
    "<str_special_character>",
    "<other_special_character>",
    "<format_effector>",
    "<base_specifier>",
    "\"_\"",
    "<letter>",
    "<letter_or_digit>",
    "<integer>",
    "<base>",
    "<based_integer>",
    "<based_literal>",
    "<basic_character>",
    "<str_basic_character>",
    "<basic_graphic_character>",
    "<str_basic_graphic_character>",
    "<basic_identifier>",
    "<bit_string_literal>",
    "<bit_value>",
    "<character_literal>",
    "<decimal_literal>",
    "<exponent>",
    "<extended_identifier>",
    "<graphic_character>",
    "<str_graphic_character>",
    "<string_literal>",
    "\"**\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"&\"",
    "\"=\"",
    "\"/=\"",
    "\">=\"",
    "\"<=\"",
    "\">\"",
    "\"<\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"!\"",
    "\".\"",
    "\",\"",
    "\"=>\"",
  };

}
